sudo: required
services:
  - docker

before_install:
  - docker build -t job4sergey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true job4sergey/docker-react npm run test
  # DockerReact-env.eba-tewjncv2.us-east-2.elasticbeanstalk.com 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-332195459451"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY